services:
  mariadb:
    image: mariadb:latest
    container_name: OrderMaster_1
    restart: always
    volumes:
      - ./init_OrderMaster.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./data:/var/lib/mysql                   # Mount a volume for data persistence (optional)
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ordermaster
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
